# NUMPY                   
                                                         -SREEKESH M, sreekeshm77@gmail.com
                                                          
**Numpy** is a powerful open-source python library used for numerical computations. it provides support for working with large, multi-dimensional arrays and matrices, along with a wide range of mathe,matical functions to operate on these arrays.

## KEY FEATURES OF NUMPY


1.   **Multi-dimensional Arrays :** At its core, NumPy provides the
ndarray object, which allows the efficient storage and operations on multi-dimensional data.
2.   **Mathematical Functions :** Includes built-in functions for Linear algebra, Fourier transforms, statistical operations, etc....

1.   **High Performance :** Written in C, it is significantly faster than Python's built-in data structures, like lists.






In [1]:
# Installation of numpy
!pip install numpy

In [2]:
#importing numpy to our notebook
import numpy as np

## CREATING ARRAYS

In [3]:
# 1-d array
arr_1 = np.array([1,2,3,4,5])
print(arr_1)

[1 2 3 4 5]


In [4]:
#2-d array
arr_2 = np.array([[1,2,3],[1,2,3]])
print(arr_2)

[[1 2 3]
 [1 2 3]]


In [5]:
#3-d array
arr_3=np.array([[[1,2],[1,2],[1,2]]])
print(arr_3)

[[[1 2]
  [1 2]
  [1 2]]]


In [6]:
# array of zeros
zeros_1=np.zeros((3,3)) #(3,3) indicates 3 rows & 3 columns
print(zeros_1)
zeros_2=np.zeros((3,3),int)  #by default, the values in arrays are float, wecan convert them into int
print(zeros_2)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [7]:
# ones array
ones=np.ones((3,3),int)
print(ones)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [8]:
# Identity matrix
#For an identity matrix, the number of rows = number of columns, Therefore no need to specify both number of rows and columns
identity=np.eye(3,dtype=int) #by default it  is also float, we can convert them into int.
print(identity)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [9]:
#Random Array
random_arr=np.random.rand(3,3)# choose 3 x 3 array with values ranging between 0 & 1
print(random_arr)

[[0.0109738  0.14760531 0.77381382]
 [0.40188254 0.22170211 0.37721007]
 [0.80323206 0.23924232 0.65669823]]


In [10]:
random_1 = np.random.randint(1,10,(3,3)) # creates an 3 x 3 array with int values ranging between 1 & 10, exclude 10
print(random_1)

[[1 3 7]
 [5 9 9]
 [5 1 7]]


In [11]:
# Range Array
range_arr= np.arange(1,7,2) # start, stop, step (exclude 7)
print(range_arr)

[1 3 5]


In [12]:
#Linspace
lin=np.linspace(2,10,5) #start,stop, number of values  (equal spacing)
print(lin)

[ 2.  4.  6.  8. 10.]


## ARRAY PPROPERTIES

In [13]:
arr_2.shape #shape of the array

(2, 3)

In [14]:
arr_2.size #total number of elements

6

In [15]:
arr_2.ndim #number of dimensions

2

In [16]:
arr_2.dtype #data type of elements

dtype('int32')

In [17]:
type(arr_2) #type of array

numpy.ndarray

## ARRAY RESHAPING

In [18]:
reshaped = arr_2.reshape(3,2) #reshaping the array
print(reshaped)

[[1 2]
 [3 1]
 [2 3]]


In [19]:
flattened = arr_2.flatten() #flattening the array  2d ---> 1d
print(flattened)

[1 2 3 1 2 3]


## ARRAY INDEXING & SLICING

In [20]:

arr=np.random.randint(1,10,(3,3))
print(arr)

[[2 4 5]
 [6 8 2]
 [9 3 7]]


In [21]:
#Basic Indexing
arr[0] #first row

array([2, 4, 5])

In [22]:
arr[1] # second row

array([6, 8, 2])

In [23]:
arr[0][2] # first row and third column

5

In [24]:
#slicing
arr[0:2] #first two rows

array([[2, 4, 5],
       [6, 8, 2]])

In [25]:
arr[0:2,0:2] #first two rows and first two columns

array([[2, 4],
       [6, 8]])

In [26]:
fancy=arr[[0,2]] #fancy indexing ----pick rows with indices 0,2
print(fancy)

[[2 4 5]
 [9 3 7]]


In [27]:
fancy=arr[[0,2],[1,2]] #fancy indexing ----pick rows with indices 0,2 and columns with indices 1,2
print(fancy)

[4 7]


## ARRAY OPERATIONS

In [28]:
#Arithematic
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1+arr2) # element wise addition
print(arr1-arr2) # element wise sub
print(arr1*arr2) # element wise multiplication
print(arr1/arr2) # element wise division
print(arr1*2) # scalar multiplication

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[2 4 6]


In [29]:
# Matrix Multiplication
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(np.dot(arr1,arr2))

[[19 22]
 [43 50]]


In [30]:
# Statistical Operations
mean=np.mean(arr1)
print(mean)
std=np.std(arr1) # standard deviation
print(std)
median=np.median(arr1)
print(median)
sum_all=np.sum(arr1)
print(sum_all)
max_value=np.max(arr1)
print(max_value)
min_value=np.min(arr1)
print(min_value)

2.5
1.118033988749895
2.5
10
4
1


In [31]:
#Aggregations
arr1=np.array([[1,2],[3,4]])
col_sum=np.sum(arr1,axis=0) #column wise sum
print(col_sum)


[4 6]


In [32]:
row_sum=np.sum(arr1,axis=1) #row wise sum
print(row_sum)

[3 7]


In [33]:
#Conditions
arr = np.array([1, 2, 3, 4, 5])
condition = arr > 3
filtered = arr[condition]  # Returns [4, 5]
print(filtered)


[4 5]


In [34]:
#Transpose ----> all rows to columns and vice versa
tr = arr1.T
print(tr)

[[1 3]
 [2 4]]


In [35]:
sorting=np.sort(arr)
print(sorting)

[1 2 3 4 5]


In [36]:
#concat
concat = np.concatenate((arr1, arr2), axis=0)  # Along rows
print(concat)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [37]:
#stacking
vstack = np.vstack((arr1, arr2))  # Vertical stack
hstack = np.hstack((arr1, arr2))  # Horizontal stack

In [38]:
print(vstack)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [39]:
print(hstack)

[[1 2 5 6]
 [3 4 7 8]]
